# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
# Mod Version Information
mod_version=2.0.1
mod_name=PizzaDelight
mod_display_name=Pizza Delight
mod_id=pizzadelight
mod_loader=neoforge

mod_license=All Rights Reserved
mod_group_id=com.tiviacz.pizzadelight
mod_authors=Tiviacz1337, SirSquidly
mod_description=Brings the tasty pizza to Minecraft as Farmer's Delight Addon!

# Minecraft Version Information
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)

# NeoForge Version Information
neo_version=21.1.209
neo_version_range=[21.0.143,)
loader_version_range=[2,)

# Mappings Information
forge_mappings_version=1.20.1
parachment_mappings_version=2023.06.26-1.20.1

# Dependency Information
jei_mcversion=1.21.1-neoforge
jei_version=19.18.0.199
